name: pubspec_extract
description: Extracts Dart pubspec.yaml file and generate pubspec.dart at build time
homepage: https://github.com/DavBfr/pubspec_extract
author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 2.0.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  args: ^2.0.0
  build: ^2.0.0
  dart_style: ^2.0.0
  logging: ^1.0.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

executables:
  pubspec_extract:
