name: pubspec_extract
description: Extracts Dart pubspec.yaml file and generate pubspec.dart at build time
homepage: https://github.com/DavBfr/pubspec_extract
author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 1.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  build: ^1.1.5
  dart_style: ^1.2.9
  yaml: ^2.1.16

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.0
