name: pubspec_extract
description: Extracts Dart pubspec.yaml file and generate pubspec.dart at build time
homepage: https://github.com/DavBfr/pubspec_extract
author: David PHAM-VAN <dev.nfet.net@gmail.com>
version: 1.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  build: ^1.2.0
  build_config: ^0.4.0
  dart_style: ^1.3.0
  yaml: ^2.2.0
